export const API_ROOT_URL = 'https://movies-v2.api-fetch.website';
// export const API_ROOT_URL = 'https://movies.api-fetch.website';

export const API_DATA_CATEGORIES = [
  'movies',
  'shows',
  'animes',
];

const moviesAndShows = [
  'action',
  'adventure',
  'animation',
  'comedy',
  'crime',
  'disaster',
  'documentary',
  'drama',
  'eastern',
  'family',
  'fan-film',
  'fantasy',
  'film-noir',
  'history',
  'holiday',
  'horror',
  'indie',
  'music',
  'mystery',
  'none',
  'road',
  'romance',
  'science-fiction',
  'short',
  'sports',
  'sporting-event',
  'suspense',
  'thriller',
  'tv-movie',
  'war',
  'western',
];

export const API_DATA_GENRES = {
  movies: moviesAndShows,
  shows: moviesAndShows,
  anime: [
    'Action',
    'Ecchi',
    'Harem',
    'Romance',
    'School',
    'Supernatural',
    'Drama',
    'Comedy',
    'Mystery',
    'Police',
    'Sports',
    'Mecha',
    'Sci-Fi',
    'Slice of Life',
    'Fantasy',
    'Adventure',
    'Gore',
    'Music',
    'Psychological',
    'Shoujo Ai',
    'Yuri',
    'Magic',
    'Horror',
    'Thriller',
    'Gender Bender',
    'Parody',
    'Historical',
    'Racing',
    'Demons',
    'Samurai',
    'Super Power',
    'Military',
    'Dementia',
    'Mahou Shounen',
    'Game',
    'Martial Arts',
    'Vampire',
    'Kids',
    'Mahou Shoujo',
    'Space',
    'Shounen Ai',
  ],
};
